### PR TITLE
Adding a formatter & linter

### PR DESCRIPTION
**Pull request by sgallag-insta**
Included changes:
- Code formatted with black.
- Added flake8 as a linter & fixed most linter errors.
- <s>Formatting should be run in a pre-commit hook.</s>
- Added lint check to CI.

### CODE REVIEW

**Comment by samedii** [comment]
Using black to format is a nice idea imo. You can turn it off locally when it fails too hard. I would say be very careful with pre-commit hooks, they can be such a pain. I'd recommend just formatting with black on save in your editor.

**Comment by sgallag-insta** [comment]
That's fair. I'm not married to the idea of the pre-commit hook, I just thought it might make things a little easier but I can see your point. As long as we have a lint check on PR I am happy

**Comment by sgallag-insta** [comment]
Notes:
- There are still a couple of linter errors left, although I'm not actually sure how to fix them, since they involve some references and I'm not sure where they're coming from :sweat_smile: @dribnet if you could take a look that would be great!
- I also haven't done any manual testing yet. Since this touches a lot of files it seems like it might be a bit of an undertaking (although breakages should hopefully be pretty obvious). If anyone feels like helping out with testing, feel free to jump in. I will also do some testing on my own.

**Comment by sgallag-insta** [comment]
Things I've tested so far:
- vqgan drawer (CLIP, SLIP)
- vdiff drawer (CLIP, SLIP)
- super_resolution drawer
- pixel drawer
- losses (aesthetic, edge, saturation, symmetry, resmem, smoothness, palette, style)

**Comment by dribnet** [comment]
Thanks for all these updates! I will try to get to this next so it is the next thing merged in.

**Comment by sgallag-insta** [comment]
I realize you are pretty busy these days, so I've gone ahead and disabled the remaining failing check (F821) for now. We can always address it later

**Comment by sgallag-insta** [comment]
Feel free to use these changes if pixray returns from stasis. Going to close the PR for now as it seems unnecessary.

**Pull request closed without merging**
