### PR TITLE
Implement a basic log for debugging

### PR DESCRIPTION
**Pull request by sgallag-insta**
Saw an open issue about improving outputs so I took a stab at it. Didn't want to do too much as I saw you may already have some updates in mind regarding the file name / directory structure.

**Summary of changes:**
- Pixray will now take an optional parameter "--debug": a boolean value that indicates whether or not to output a debug log with the final output.
- The debug log currently includes the settings used to generate an image. (More can be added later).
- A reusable file path calculation function in utility class.
- Add some unit tests.

### CODE REVIEW

**Comment by sgallag-insta** [comment]
Hi @dribnet, you're probably really busy over the holidays but going to ping you here just in case you haven't checked PRs recently :) Once I get your feedback I can look into expanding this some more

**Comment by dribnet** [comment]
Thanks so much @sgallag-insta - this looks outstanding. I am taking a bit of a break but will be getting back into this soon and am excited to try this out. 👍

**Comment by sgallag-insta** [comment]
Based on discussion in the discord, it sounds like these changes are obsolete. Setting information should be embedded directly in output image metadata. Closing

**Comment by dribnet** [comment]
Well not obsolete - but I think it was useful as part of a [larger planned change to have multiple outputs](https://github.com/dribnet/pixray/issues/1) per run. So I think I will reuse this as part of that future refactor if that's OK.

**Comment by sgallag-insta** [comment]
Hmm... I could see how the file name parsing could be (temporarily) useful until the file names are determined based on time/seed. The generation settings would be useful in a debug log, but I think we'd want that structured quite differently from what I have here. Let me see if I can clean this up a bit

**Comment by dribnet** [comment]
Sorry I didn't give prompt feedback on this and it's now gone stale. I'd be up for revisiting this if you'd like.

**Comment by sgallag-insta** [comment]
No worries, I know you are busy. Yes, it would be great to get this one closed out. I will add the `output_dir` :+1:

**Comment by sgallag-insta** [comment]
Ok, this should be a bit more elegant. Seems like it's working pretty good but I haven't tested the video path yet. There is one noteworthy quirk with the behaviour though.

The default behaviour of the Path command I used would actually allow an empty filename, in which case it would just create the filename at the end of the path:
`output_dir="/test"
output_file='',
final path='/test.png'`

I have explicitly disabled this since I found it a bit weird. It's noteworthy though that the opposite behaviour still holds true:

`output_dir=''
output_file='/test.png'
final path='/test.png'`

Which means that as it stands currently, the `output` param should be completely backwards compatible, but `output_dir` is an optional separate addition.

**Comment by dribnet** [comment]
Thanks! If we have an output directory, is there any harm to always having an output log file?

**Comment by dribnet** [comment]
Sounds good. I think we could perhaps reintroduce it later as a LOG_LEVEL which could be set to 0 for no logging at all, etc. But I think at the point where we have a unique output directory per run we can start chucking all sorts of things in there (last z, output logs, svg files for the diffvg drawers, etc) at least at the end of the run.

**Comment by sgallag-insta** [comment]
Good call! Yes, LOG_LEVEL would definitely be a much more useful parameter in this case :slightly_smiling_face:

**Comment by dribnet** [comment]
This is now in testing in the `future` branch. If you do any further work to this, please make sure to cherry-pick the two commits listed above first.

**Comment by dribnet** [comment]
Working well for me.

After using a bit I am wondering whether `--output_dir` should be simply `--outdir` or even just `--output` (replacing the previous interpreation of this settings - and then we introduce `--outfile` perhaps). Anyone with thoughts on this? It's a small code change, but a pretty big breaking change to existing scripts, etc. which is why I have been putting it off for a while.

**Comment by dribnet** [comment]
Just making a note to myself that I'm also really excited that we now have a way to save all intermediate outputs as separate files and make a video, so maybe this should now also be on by default. 🤔

**Comment by dribnet** [comment]
another wish: output a settings.yaml on every run that can be used for future runs via --setings_file. there is already smarts used for metadata to build a dictionary of only updated settings and grab the random key used, etc. this just needs to be reused and dumped into a yaml as well.

**Comment by sgallag-insta** [comment]
I don't have super strong feelings on the parameter names, I think either solution sounds good to me. Although, `outfile` does make more sense than `output` to me, if we are to keep `outdir`. Given that you've pointed out this is likely a breaking change for many scripts though, I wonder if we should also try to include the change about generating the filename based on seed/time before this is merged. Get all of the pain out of the way in one go. I can try to get that one up; it seems like it should be fairly straightforward.

**Comment by sgallag-insta** [comment]
It looks like you've already merged a commit which includes tokens in the directory/filename. So in this case maybe I'll spend some time working on the percentage/iteration issue we discussed earlier instead

**Pull request closed without merging**
