### PR TITLE
New option to load from yaml without using run.py

### PR DESCRIPTION
**Pull request by syllebra**
@dribnet Can you please check and merge this feature?

It is meant to take a new argument: `--config-file <path_to_yaml>` without using `run.py `script.
(Sorry for delays, this is my first PR on a repo I forked ;))

See ya! And, btw, great job on pixray...

### CODE REVIEW

**Comment by dribnet** [comment]
Thanks for this. What do people think of calling this `--settings` instead of `--config-file`?

Another crazy thought I had was perhaps letting the settings file be an allowed default so one could simply say `pixray.py settings.yaml`. 🤔

**Comment by sgallag-insta** [comment]
I would lean towards `--settings`, personally. Neutral on whether or not to make it an allowed default

**Comment by dribnet** [comment]
For now I've simply renamed it to `config_file` (from `config-file` for consistency with other settings). 

Worked great in testing. One nice application is that settings for the replicate models are already in the repo in yaml format and so can now be loaded now from the command line as defaults, and any other arguments will override these. So this is a convenient way to load "vdiff defaults" with a different prompt and output file:

```bash
python pixray.py \
  --prompts "fat albert" \
  --output outputs/jan22/albert_29_01.png \
  --config_file cogs/pixray_vdiff.yaml
```
albert_29_01

This is merged now into `future` and should be part of the next release after more testing.

**Comment by syllebra** [comment]
Good. But there is one thing not working, not specially due to this PR:
```
python pixray.py \
  --prompts "fat albert" \
  --output outputs/jan22/albert_29_01.png \
  --config_file cogs/pixray_vdiff.yaml
  --drawer vqgan
```

Simply because vqgan (I think CLI args override yaml, but maybe it depends on the arguments order) does not accept vdiff parameters. This is also true in pure command line command... It either need to be documented or fixed (ignore parameter of other drawers with a warning instead of throwing error).

**Comment by dribnet** [comment]
Thanks - I've been thinking about this but I'm not sure there is an easy fix. The settings code aggressively tries to find settings that are "incompatible" to help people find common errors like misspelling keys - and in this case the yaml has settings that are incompatible with the drawer. But I'll think about this more and we can add some sort of capability for "overriding" or "ignoring" settings if this gets too annoying.

**Pull request merged**
