### PR TITLE
Super resolution drawer

### PR DESCRIPTION
**Pull request by samedii**

### CODE REVIEW

**Comment by dribnet** [comment]
Great stuff, thanks! This is now in testing in the `future` branch. If you do any further work to this, please make sure to cherry-pick the commit listed above (2667d97) first.

**Comment by dribnet** [comment]
Seems to be working great. Please take a test drive of the `future` branch and let me know if you see any issues.

super2

**Comment by samedii** [comment]
Noticed a change that breaks installation
https://github.com/pixray/pixray/commit/2667d970de3445266911b6e930ea26e8b9709982

**Comment by samedii** [comment]
Looks like it works quite well. I think it's probably strongest with an init image much like the pixeldrawer
image

**Pull request merged**
