### PR TITLE
Parse units in arguments

### PR DESCRIPTION
**Pull request by sgallag-insta**
**Summary of changes:**
- Added a new `parse_unit` function that parses strings with units ("20 iterations", "50%", etc) to a raw iteration integer.
- Refactored how parameters with pipes are handled slightly.
- Overlay related arguments now use strings with units specified rather than integers.
- Added test cases.

Haven't had time to hook up the other arguments yet but I can continue with that.

### CODE REVIEW

**Comment by dribnet** [comment]
This looks great. What do you think though of making this backwards compatible for now so that raw numbers are interpreted as iterations still?

**Comment by sgallag-insta** [comment]
I did consider this. The main reason I didn't do it here is because it does mean we will have to bypass the type checking for the ArgParser (i.e. the parameter will have to support both strings _AND_ ints). That said, I do generally have a preference towards backwards compatible changes so I will update that

**Comment by dribnet** [comment]
Couldn't we just leave it as string, but just try int parsing + appending "%" as a fallback?

**Comment by sgallag-insta** [comment]
Yeppp, I think that would work. It just bothers me a bit because I like strong typing. That said, having just manually tested this implementation, something needs to change. It currently _only_ works with integer input :sweat_smile: Going to play around with this a bit more today

**Comment by sgallag-insta** [comment]
Ok, I didn't realize the argparser was just going to allow ints in place of strings that easily :slightly_smiling_face:

**Comment by dribnet** [comment]
Awesome refactoring. Finally got this merged into future and seems to be working great. After a bit more testing I will probably expand this use to also cover other use cases - eg: `init_image_alpha=50%` 👍

**Comment by sgallag-insta** [comment]
Yes, sorry I did kinda leave things sitting around a little incomplete. I made the mistake of setting up Pixray locally without a `venv`, so it has made development/testing more painful than it needs to be. 😄  I do have some more ideas I'd like to contribute though; I'll have to see if I can get my local environment set up a little better

**Pull request merged**
