### PR TITLE
Aesthetic loss by DazhiZhong

### PR DESCRIPTION
**Pull request by samedii**

### CODE REVIEW

**Comment by dribnet** [comment]
I think `aesthetic_weight` is unnecessary here, but we should probably instead scale this by a constant so that the default weight=0 applies a reasonable amount.

**Comment by dribnet** [comment]
This is now in testing in the future branch. If you do any further work to this branch, please make sure to cherry-pick the fixes 8d59822 (which I forgot to tag in the commit) as well the commit listed above (73a6a4c).

**Comment by dribnet** [comment]
I have a version I think is working well for me and have taken a stab at renaming the options and adjusting the weight constant. For reference here's my pixelart "deep ocean monsters" before:

monsters3


and after with the same settings but adding the aesthetic loss at the current default value:

monsters7

That seems like a clearly noticeable but not overpowering effect.

Here's the command line version of that latter one for posterity.
```bash
python pixray.py \
  --size 840 160 \
  --pixel_size 210 40 \
  --quality better \
  --drawer pixel \
  --custom_loss aesthetic,saturation:0.5,smoothness:2.0 \
  --smoothness_type log \
  --prompt 'deep ocean monsters #pixelart' \
  --output_dir outputs/feb22/monsters_02_07
```

Note in testing I had the aesthetic weighting constant set to 5x the current value and it was way too powerful. Eg:

monsters6

So I think the current one is pretty close to a good default but maybe it could still be dialed up a bit.

Can someone try this out in the future branch with vdiff, etc. and let me know if it seems to be working well for them?

**Comment by samedii** [comment]
Without aesthetic and with. It's a little hard to tell what's going to happen with this loss
image
image

**Comment by samedii** [comment]
image

**Comment by dribnet** [comment]
I'm finding the current weight for aesthetic loss good at "normal" scale for vqgan and vdiff.

out2
out3

but a bit overpowering for pixel and fft.

out4
out5

however backing off to aesthetic:0.2 for those seems to give reasonable output
out7
out8

SO: it would be nice if we could find a value that worked independent of drawer and size of image, but this might not be so simple...

**Pull request merged**
